# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# https://www.mkdocs.org/getting-started/
# https://www.mkdocs.org/user-guide/
# https://squidfunk.github.io/mkdocs-material/
# https://guts.github.io/mkdocs-rss-plugin/
site_name: My GitHub Blog
site_url: https://maroph.github.io/blog/
site_description: My GitHub repositories related blog
site_author: Manfred Rosenboom (maroph)

repo_url: https://github.com/maroph/blog/
repo_name: maroph/blog
edit_uri: edit/main/docs

theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    font: false
    language: en
#    logo: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
    logo: assets/128px-Feed-icon.svg.png
    direction: ltr
# https://www.favicon.cc/?action=icon&file_id=11659#
    favicon: assets/favicon.ico
    features:
        - header.autohide
        - content.action.edit
        - content.action.view
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.prune
        - navigation.sections
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - search.suggest
        - search.highlight
        - toc.follow
#        - toc.integrate
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right

nav:
    - Blog: index.md

docs_dir: docs
site_dir: site

use_directory_urls: false
strict: true

copyright: Copyright (c) 2025 CC-BY 4.0 <a href="https://maroph.github.io/">Manfred Rosenboom</a>

markdown_extensions:
    - attr_list
# available icons, emojis: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables

plugins:
    - meta:
          enabled: true
    - privacy:
          enabled: true
          cache: true
    - search:
          enabled: true
          lang: en
    - blog:
        enabled: true
        authors: true
        blog_dir: .
        blog_toc: true
        draft: false
        draft_on_serve: false
        draft_if_future_date: false
        pagination: true
        pagination_per_page: 10
        pagination_url_format: "page/{page}"
        post_date_format: "dd. MMMM YYYY, H:mm"
        pagination_if_single_page: false
        post_excerpt: optional
        post_excerpt_separator: "<!-- more -->"
        post_readtime: false
        archive: true
        archive_name: Archive
        archive_date_format: yyyy
        archive_url_format: "archive/{date}"
        archive_toc: true
        categories: true
        categories_name: Categories
        categories_url_format: "category/{slug}"
        categories_toc: true
        categories_allowed:
            - Announcement
            - General
    - rss:
        enabled: true
        abstract_chars_count: 160
        abstract_delimiter: "<!-- more -->"
        categories:
            - categories
            - tags
        match_path: "posts/.*"
        date_from_meta:
            as_creation: "date"
            as_update: "updated"
            datetime_format: "%Y-%m-%d %H:%M"
            default_time: "12:00"
            default_timezone: Europe/Berlin
        feed_ttl: 1440
        image: https://maroph.github.io/blog/assets/128px-Feed-icon.svg.png
        json_feed_enabled: false
        length: 10
        use_git: false
        use_material_blog: true

extra:
    generator: true
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/maroph
          name: github.com/maroph
        - icon: fontawesome/brands/mastodon
          link: https://mastodon.social/@maroph
          name: mastodon.social/@maroph
